### PR TITLE
Prefer no braces for inline fat arrow functions

### PR DESCRIPTION
**Pull request by dwaltrip**
I feel that this reads more cleanly.

### CODE REVIEW

**Comment by dwaltrip** [comment]
Just realized you can leave off the initial parentheses if there is only one argument (or if you only care about the first argument):
`var names = people.map(person => person.name);`

**Comment by trisrael** [comment]
Well that's amazing.

`return person.name` though right?

**Comment by dwaltrip** [comment]
Nope, if the function body is a single expression, and you leave out the surrounding braces, then you don't need the keyword `return`. It makes the code very pretty & readable!

**Comment by alexgb** [comment]
Can I entice you to instead submit a PR to merge the ES6 airbnb style guide which already covers this case https://github.com/airbnb/javascript#arrow-functions?

**Comment by dwaltrip** [comment]
Yes, that sounds like a good idea. I'll do it next week. We are cranking hard this week to release the student playlist changes.

**Comment by alexgb** [comment]
Closing in favor of #12

**Pull request closed without merging**
