### PR TITLE
Merge Airbnb's latest ES6 styleguide

### LINKED ISSUE #10: Import sorting
Can we change import sorting so that destructured imports fall to the bottom? https://github.com/AltSchool/javascript#imports

I typically use `F5` to sort groups of items which alphabetically moves desctructured imports down because of the '{` character. I also find this easier to read in my opinion as the object notation makes it stand out from the rest of the items.

What do you think?

### PR DESCRIPTION
**Pull request by alexgb**
Merged in latest ES6 version of Airbnb's styleguide. Kept anything Ember specific and reverted our change to `//` for multiline comments, as the `/* */` syntax is actually required for jsdoc parsing in Slate.

### CODE REVIEW

**Comment by jeffreybiles** [comment]
Looks like this may need a rebase

**Comment by benshine** [comment]
@jeffreybiles -- what makes you say you think it needs a rebase? it looks like we're pulling in a giant pile of commits from airbnb, which seems right.

**Comment by jeffreybiles** [comment]
@benshine I pattern-matched and assumed that the commit that @alexgb created with the same name as the PR was the one we wanted and the others should be rebased away... but it probably works different when pulling in outside code.  Ignore my comment if you like.

**Comment by benshine** [comment]
Ah, I gotcha -- but then the title of the PR changed :)

**Pull request merged**
